### ISSUE TITLE
DC misfit map rotated

### ISSUE THREAD

**Issue by SeismoFelix** [thurinj/mtuq#3]
Hi Julien, 

The DC CMA-ES solutions work and find almost the same solution as when using the grid search. However, the misfit plot is rotated for the strike-dip and strike-slip plots. 

Thanks for taking a look into this. 

<img width="2541" alt="Screenshot 2023-12-15 at 11 34 21 AM" src="https://github.com/thurinj/mtuq/assets/18186011/88a19a85-d38d-4ccf-acc9-e0356a34e236">

**Comment by thurinj** [comment]
Thanks @SeismoFelix for pointing that up. I've addressed the issue in the commit: a710d70e249991fd0738103bfaab4f35631e6357

It was a matter of transposing the array before plotting. Note that the mean was plotted in the right spot, but not the background values map!

I just ran through the main example and it yields this:

![DC_Misfits](https://github.com/thurinj/mtuq/assets/63735192/7504acb9-52c6-429f-aa80-6628536c4e76)

So I think we're good to go on this one. Thanks!
